import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  containerPage: {
    flex: 1,
  },
  containerForm: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  image: {
    flex: 1,
    justifyContent: 'center',
    resizeMode: 'cover',
  },
  form: {
    position: 'relative',
    paddingHorizontal: 16,
    paddingTop: 92,
    paddingBottom: 40,
    backgroundColor: '#fff',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },
  title: {
    marginBottom: 32,
    fontFamily: 'Roboto-Medium',
    lineHeight: 35,
    fontSize: 32,
    textAlign: 'center',
  },
  containerAvatar: {
    position: 'absolute',
    top: -60,
    alignSelf: 'center',
    width: 120,
    height: 120,
    backgroundColor: '#F6F6F6',
    borderRadius: 16,
    overflow: 'hidden',
  },
  avatar: {
    width: 120,
    height: 120,
    objectFit: 'cover',
  },
  btnDeleteAvatar: {
    zIndex: 10,
    position: 'absolute',
    top: 22,
    right: 117,
    borderRadius: '50%',
    backgroundColor: '#fff',
  },
  inputWrapper: {
    position: 'relative',
    justifyContent: 'center',
  },
  input: {
    paddingLeft: 16,
    marginBottom: 16,
    height: 50,
    fontFamily: 'Roboto-Regular',
    fontSize: 16,
    lineHeight: 19,
    color: '#212121',
    borderWidth: 1,
    borderRadius: 8,
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 43,
    marginBottom: 16,
    paddingVertical: 16,
    backgroundColor: '#FF6C00',
    borderRadius: 100,
  },
  buttonShowPassword: {
    position: 'absolute',
    right: 0,
    alignItems: 'center',
    paddingVertical: 15,
    paddingRight: 16,
  },
  buttonTitle: {
    fontFamily: 'Roboto-Regular',
    fontSize: 16,
    lineHeight: 19,
    color: '#ffffff',
  },
  redirectLinkTitle: {
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
    fontSize: 16,
    lineHeight: 19,
    color: '#000080',
  },
  text: {
    marginRight: 4,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
    fontSize: 16,
    lineHeight: 19,
  },
  wrapTextAndLink: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
});
