import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 32,
    paddingBottom: 8,
    paddingHorizontal: 16,
    backgroundColor: '#ffffff',
  },
  imageContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  image: {
    borderRadius: 8,
    marginBottom: 8,
  },
  inputWrap: {
    position: 'relative',
    justifyContent: 'center',
  },
  input: {
    paddingLeft: 12,
    paddingRight: 46,
    // minHeight: 32,
    paddingBottom: 4,
    fontFamily: 'Roboto-Regular',
    fontSize: 16,
    lineHeight: 19,
    color: '#212121',
    backgroundColor: '#F6F6F6',
    borderWidth: 1,
    borderColor: '#E8E8E8',
  },
  btnSendComment: {
    position: 'absolute',
    right: 8,
    alignItems: 'center',
    justifyContent: 'center',
    width: 24,
    height: 24,
    backgroundColor: '#FF6C00',
    borderRadius: 8,
  },
  itemComments: {
    flexDirection: 'row',
    marginBottom: 32,
  },
  imageWrap: {
    marginRight: 16,
  },
  imageAvatar: {
    width: 28,
    height: 28,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#BDBDBD',
  },
  textCommentsWrap: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.03)',
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    borderTopRightRadius: 8,
  },
  text: {
    marginBottom: 8,
    width: 267,
    fontFamily: 'Roboto-Regular',
    fontSize: 14,
    lineHeight: 18,
    color: '#212121',
  },
  date: {
    textAlign: 'right',
    fontFamily: 'Roboto-Regular',
    fontSize: 10,
    lineHeight: 12,
    color: '#BDBDBD',
  },
});
